const SECTION = {
  STUDENT_CODE: "STUDENT",
  LECTURER_CODE: "LECTURER", 
  ADMIN_CODE: "ADMIN",
  STUDENT: 10,
  LECTURER: 50,
  ADMIN: 100
}

const GOOGLE_SERVICE = {
  DRIVE: "DRIVE",
  GMAIL: "GMAIL"
}

module.exports = {
  SECTION,
  GOOGLE_SERVICE
}